name       : haskell-x509-system
version    : 1.6.4
release    : 1
source     :
    - http://hackage.haskell.org/package/x509-system-1.6.4/x509-system-1.6.4.tar.gz : d98ef028855ad73a872ed86026f205aba383378bf1e63462c5d3e4733b60ff4c
license    : BSD-3-Clause
component  : programming.haskell
summary    : System X.509 handling
description: |
    System X.509 handling
builddeps  :
    - haskell-cabal-install
    - haskell-x509-store
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
