name       : haskell-x509-system
version    : 1.6.6
release    : 3
source     :
    - https://hackage.haskell.org/package/x509-system-1.6.6/x509-system-1.6.6.tar.gz : 40dcdaae3ec67f38c08d96d4365b901eb8ac0c590bd7972eb429d37d58aa4419
license    : BSD-3-Clause
component  : programming.haskell
summary    : System X.509 handling
description: |
    System X.509 handling
builddeps  :
    - haskell-cabal-install
    - haskell-x509-store-devel
rundeps    :
    - devel:
        - haskell-x509-store-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
